# Google Authentication

# Initiate Google Login
GET /auth/google HTTP/1.1
Host: localhost:3000

# Callback URL (After Google Login)
GET /auth/google/user HTTP/1.1
Host: localhost:3000
Authorization: Bearer <your_google_access_token>
