### Register a new user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "princeleepraise@gmail.com",
    "password": "password"
}

### Login with existing user
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "pdfraise9@mail.com",
    "password": "password"
}


### Verify-email
POST http://localhost:3000/auth/verify-email
# ?token= please add generated token as query

